version: '3.8'

services:
  database:
    container_name: travelapp
    image: postgres
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./db_init/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./db_data:/var/lib/postgres/data/
    ports:
      - 5432:5432
    env_file:
      - env/.env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5